version: 2.7.13+.{build}
clone_depth: 5
branches:
  only:
    - master
    - /\d\.\d/
    - buildbot-custom
cache:
  - externals -> PCbuild\*
build_script:
- cmd: PCbuild\build.bat -e
- cmd: PCbuild\python.exe -m test.pythoninfo
test_script:
- cmd: PCbuild\rt.bat -q -uall -u-cpu -rwW --slowest -j2
environment:
  HOST_PYTHON: C:\Python36\python.exe

# Only trigger AppVeyor if actual code or its configuration changes
only_commits:
  files:
    - .github/appveyor.yml
    - .gitattributes
    - Grammar/
    - Include/
    - Lib/
    - Modules/
    - Objects/
    - PC/
    - PCBuild/
    - Parser/
    - Programs/
    - Python/
    - Tools/
